version: 0.2

phases:

  build:
    commands:

      - echo Deploying Attendance App

      - ssh ec2-user@52.66.211.25 "
          cd ATTENDANCE_APPLICATION &&
          git pull origin main &&
          pip3 install -r requirements.txt &&
          pkill -f app.py || true &&
          nohup python3 app.py > output.log 2>&1 &
        "
